// <auto-generated />
namespace MyShop.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_OrderView_In_Order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_OrderView_In_Order));
        
        string IMigrationMetadata.Id
        {
            get { return "202211290604545_add_OrderView_In_Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
